services:
  backend:
    image: golang:latest
    container_name: backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/go/app
  db:
    image: mariadb:latest
    container_name: db
    tty: true
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
