services:
  backend:
    image: golang:latest
    container_name: backend
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /go/app
  db:
    image: mariadb:latest
    container_name: db
    tty: true
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./sql_init
        target: /docker-entrypoint-initdb.d
