services:
  backend:
    image: golang:latest
    container_name: backend
    tty: true
    ports:
      - 8080:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      S3_ACCOUNT_ID: ${S3_ACCOUNT_ID}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${S3_ACCESS_KEY_SECRET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      IMAGE_REPOSITORY_URL: ${IMAGE_REPOSITORY_URL}
    volumes:
      - type: bind
        source: ./
        target: /go/app
  db:
    image: mariadb:latest
    container_name: db
    tty: true
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./sql_init
        target: /docker-entrypoint-initdb.d
