services:
  backend:
    labels:
      - traefik.enable=true
      - traefik.docker.network=sns-network
      - traefik.http.routers.backend.entryPoints=web
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.services.backend.loadbalancer.server.port=8080
    env_file:
      - .env
      - .env.prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: backend
    tty: true
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: mariadb:11.6
    container_name: db
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./sql_init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./sql_data
        target: /var/lib/mysql
    healthcheck:
      test: "mariadb-admin ping -h localhost -u root -p$$MARIADB_ROOT_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10
networks:
  default:
    name: sns-network