// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLike = "likes"

// Like mapped from table <likes>
type Like struct {
	ID     string `gorm:"column:id;type:varchar(100);primaryKey" json:"id"`
	PostID string `gorm:"column:post_id;type:varchar(100);not null;index:likes_posts_FK,priority:1" json:"post_id"`
	UserID string `gorm:"column:user_id;type:varchar(100);not null;index:likes_users_FK,priority:1" json:"user_id"`
}

// TableName Like's table name
func (*Like) TableName() string {
	return TableNameLike
}
