// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          string     `gorm:"column:id;type:varchar(100);primaryKey" json:"id"`
	UserName    *string    `gorm:"column:user_name;type:varchar(191);uniqueIndex:uni_users_user_name,priority:1" json:"user_name"`
	DisplayName *string    `gorm:"column:display_name;type:longtext" json:"display_name"`
	Biography   *string    `gorm:"column:biography;type:text" json:"biography"`
	IconURL     *string    `gorm:"column:icon_url;type:longtext" json:"icon_url"`
	BgImageURL  *string    `gorm:"column:bg_image_url;type:longtext" json:"bg_image_url"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
