// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID        string    `gorm:"column:id;type:varchar(100);primaryKey" json:"id"`
	PostID    string    `gorm:"column:post_id;type:varchar(100);not null;index:comments_posts_FK,priority:1" json:"post_id"`
	UserID    string    `gorm:"column:user_id;type:varchar(100);not null;index:comments_users_FK,priority:1" json:"user_id"`
	Content   string    `gorm:"column:content;type:text;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;not null" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
